# Мир, в котором запрещено использовать предметы из плагина.
# Игрокам нельзя нажать ПКМ этими предметами: они не тратятся,
# но вешается бесконечная перезарядка и выводится сообщение.
#
# Можно указать несколько миров списком:
# spawn-world:
#   - 'spawn'
#   - 'spawn_nether'
spawn-world: 'spawn'
